2018-01-17 12:40:48,679 ERROR: Exception on /index [GET] [in /Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/glowatsk/microwebsite/app/routes.py", line 29, in index
    posts = current_user.followed.posts().all()
AttributeError: 'AppenderBaseQuery' object has no attribute 'posts'
2018-01-17 12:42:57,307 INFO: Microsite Setup [in /Users/glowatsk/microwebsite/app/__init__.py:45]
2018-01-17 12:43:02,651 ERROR: Exception on /index [GET] [in /Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/glowatsk/microwebsite/app/routes.py", line 29, in index
    posts = current_user.followed.posts().all()
AttributeError: 'AppenderBaseQuery' object has no attribute 'posts'
2018-01-17 12:43:28,671 INFO: Microsite Setup [in /Users/glowatsk/microwebsite/app/__init__.py:45]
2018-01-17 12:43:34,650 ERROR: Exception on /index [GET] [in /Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/glowatsk/microwebsite/app/routes.py", line 29, in index
    posts = current_user.followed.posts().all()
AttributeError: 'AppenderBaseQuery' object has no attribute 'posts'
