2018-01-17 12:45:55,393 ERROR: Exception on /user/1234 [GET] [in /Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/glowatsk/microwebsite/app/routes.py", line 79, in user
    return render_template('user.html', user=user, posts=posts)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/glowatsk/microwebsite/app/templates/_post.html", line 5, in template
    <a href="{{ url_for('user, username=post.author.username }}">{{ post.author.username }}</a>
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/glowatsk/microwebsite/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/glowatsk/microwebsite/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/glowatsk/microwebsite/app/templates/user.html", line 22, in block "content"
    {% include '_post.html' %}
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/glowatsk/microwebsite/app/templates/_post.html", line 5, in template
    <a href="{{ url_for('user, username=post.author.username }}">{{ post.author.username }}</a>
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 875, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 620, in parse_tuple
    args.append(parse())
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 450, in parse_or
    left = self.parse_and()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 459, in parse_and
    left = self.parse_not()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 470, in parse_not
    return self.parse_compare()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 547, in parse_unary
    node = self.parse_postfix(node)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 676, in parse_postfix
    node = self.parse_call(node)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/parser.py", line 754, in parse_call
    token = self.stream.expect('lparen')
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/lexer.py", line 388, in expect
    next(self)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/lexer.py", line 359, in __next__
    self.current = next(self._iter)
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/lexer.py", line 562, in wrap
    for lineno, token, value in stream:
  File "/Users/glowatsk/microwebsite/venv/lib/python3.6/site-packages/jinja2/lexer.py", line 739, in tokeniter
    name, filename)
jinja2.exceptions.TemplateSyntaxError: unexpected char "'" at 124
2018-01-17 12:46:27,633 INFO: Microsite Setup [in /Users/glowatsk/microwebsite/app/__init__.py:45]
